spring:
  datasource:
    url: jdbc:mysql://47.97.179.125:3306/qianye_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: qianye
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 47.97.179.125
    password: cjt123
    connect-timeout: 10s
#    redis配置
#      lettuce:
#        pool:
#          # 连接池最大连接数
#          max-active: 150
#          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          max-wait: 5000ms
#          # 连接池中的最大空闲连接
#          max-idle: 100
#          # 连接池中的最小空闲连接
#          min-idle: 50
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto # 主键自增

